pagopa/corporate-site-fe

snapshot.gql
src/hooks/useLocalizedQuery.ts
src/partials/Footer/Footer.tsx
src/partials/MenuFooter/MenuFooter.tsx
src/partials/MenuService/MenuService.tsx
src/partials/Socials/Socials.tsx

removed useStaticQuery usage from useLocalizedQuery hook

fix(useLocalizedQuery): useStaticQuery bug

---

gatsby-config.ts
snapshot.gql
src/components/Article/Article.tsx
src/components/Image/Image.tsx
src/components/Pagination/Pagination.sass
src/components/Pagination/Pagination.tsx
src/components/Pagination/index.ts
src/components/Remark/index.ts
src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx
src/components/SharedBlocks/PressRelease/PressReleaseList.tsx
src/components/SharedBlocks/UniversityCollaboration/UniversityCollaborationList.tsx

- pagination component
- university pagination refactored
- pagination newsletter
- pagination news
- pagination events
- pagination pressRelease
- minor style fixes

feat: client pagination

---

gatsby-config.ts
snapshot.gql
src/components/SEO/SEO.tsx
src/hooks/useSiteMetadata.tsx
src/pages/lavora-con-noi/{StrapiJobposition.slug}.tsx
src/pages/media/comunicati-stampa/{StrapiPressRelease.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiEvent.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiPost.slug}.tsx
src/pages/media/newsletter-outer-space/{StrapiNewsletter.slug}.tsx
src/pages/prodotti-e-servizi/{StrapiProject.slug}.tsx
src/pages/{StrapiPage.permalink}.tsx

- uses siteMetadata defaults
- added page title as metaTitle fallback
- improved metaSocial definition
Fixes # [cpp-91](https://pagopa.atlassian.net/browse/CPP-91)

[CPP-91] Seo gatsby defaults

---

.github/workflows/deploy-aws.yml

@vito80ba to let github to be aware of a new github action it's needed to release it in the main branch. Can I?

feat: Github action to deploy on AWS

---

src/pages/index.tsx

Added a local empty index page to avoid the redirection loop.
Fixes # [cpp-119](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-119)

[CPP-119] Redirection Loop

---

.gitignore
gatsby-config.ts
package.json
src/locales/en/translations.json
src/locales/it/translations.json
src/pages/404.tsx
src/pages/media/comunicati-stampa/{StrapiPressRelease.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiEvent.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiPost.slug}.tsx
src/pages/media/newsletter-outer-space/{StrapiNewsletter.slug}.tsx
src/pages/prodotti-e-servizi/{StrapiProject.slug}.tsx
src/pages/{StrapiCTAlias.from}.tsx
src/pages/{StrapiPage.permalink}.tsx
yarn.lock

- i18nex config
- empty locales translations file to avoid console errors
- page queries for localization strings
Fixes # [cpp-118](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-118)

[CPP-118]: 18next config

---

.gitignore
gatsby-config.ts
package.json
src/locales/en/translations.json
src/locales/it/translations.json
src/pages/404.tsx
src/pages/media/comunicati-stampa/{StrapiPressRelease.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiEvent.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiPost.slug}.tsx
src/pages/media/newsletter-outer-space/{StrapiNewsletter.slug}.tsx
src/pages/prodotti-e-servizi/{StrapiProject.slug}.tsx
src/pages/{StrapiCTAlias.from}.tsx
src/pages/{StrapiPage.permalink}.tsx
yarn.lock

Reverts pagopa/corporate-site-fe#101

Revert "[CPP-118]: 18next config"

---

.gitignore
gatsby-config.ts
package.json
src/locales/en/translations.json
src/locales/it/translations.json
src/pages/404.tsx
src/pages/media/comunicati-stampa/{StrapiPressRelease.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiEvent.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiPost.slug}.tsx
src/pages/media/newsletter-outer-space/{StrapiNewsletter.slug}.tsx
src/pages/prodotti-e-servizi/{StrapiProject.slug}.tsx
src/pages/{StrapiCTAlias.from}.tsx
src/pages/{StrapiPage.permalink}.tsx
yarn.lock

Reverts pagopa/corporate-site-fe#103

Revert "Revert "[CPP-118]: 18next config""

---

gatsby-config.ts
snapshot.gql
src/components/SharedBlocks/BlocksRenderer.tsx
src/components/SharedBlocks/Jobposition/JobpositionList.tsx

Added missing joblisting components.
Fixes # [cpp-128](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-128)

[CPP-128] Missing Joblist components

---

src/components/Article/Article.sass
src/components/Pagination/Pagination.tsx
src/components/SharedBlocks/BlocksRenderer.tsx
src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx
src/components/SharedBlocks/PressRelease/PressReleaseList.tsx
src/pages/{StrapiPage.permalink}.tsx

- fixes Articles images
- fixes Article & PressRelease style
- PressRelease & Articles preview
Fixes # [cpp-124](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-124)
Fixes # [cpp-125](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-125)

[CPP-124-125] Media components

---

src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx

Fixes a warning caused by sharp image graphql queries
Fixes # [cpp-124](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-124)
Fixes # [cpp-125](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-125)

[CPP-124\125] Images Queries

---

src/components/SharedBlocks/Intro/Intro.tsx
src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx
src/components/SharedBlocks/Visual/Visual.tsx
src/components/SharedBlocks/VisualText/VisualText.tsx

- Improves VisualText Component syling
- Improves Intro Component syling
- Fixes news and events styling
Fixes # [cpp-129](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-129)
Fixes # [cpp-124](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-124)

[CPP-129-124] Style Fixes

---

src/components/SharedBlocks/ProjectsCarousel/ProjectsCarousel.sass
src/components/SharedBlocks/ProjectsCarousel/ProjectsCarousel.tsx

Improves ProjectsCarousel syling
Fixes # [cpp-131](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-131)

[CPP-131] Carousel Styling

---

gatsby-config.ts
src/hooks/useRevealTextAnimation.ts

Solves hydration errors logged to console using useEffect hook for reveal text animation
Fixes # [cpp-132](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-132)

[CPP-132] Hydration Errors

---

src/components/Article/Article.sass
src/components/Article/Article.tsx
src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx

Fixes and refactor the newsletter list component style. 
Fixes # [cpp-138](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-138)

[CPP-138] Newsletter Listing Style Fix

---

gatsby-browser.js
src/utils/cookies.ts

Google analytics cookies removal
- adds cookies utils functions
- expire _ga cookies client side with wrapRootElement
Fixes # [cpp-141](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-141)

[CPP-141] Delete _ga cookies

---

gatsby-node.js
src/components/SharedBlocks/Newsletter/NewsletterList.tsx
src/components/SharedBlocks/PostEvents/PostEventsList.tsx
src/pages/media/news-ed-eventi/{StrapiEvent.slug}.tsx
src/pages/media/news-ed-eventi/{StrapiPost.slug}.tsx
src/pages/opportunita/fondo-innovazione/comunicati/{StrapiInnovationAnnouncement.slug}.tsx

Overrides publishedAt with publishOverride.
Fixes # [cpp-139](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-139)

[CPP-139] Publish date override

---

package.json
src/utils/cookies.ts
yarn.lock

Uses js-cookies for handling cookies and refactoring
Fixes # [cpp-141](https://pagopa.atlassian.net/jira/software/projects/CPP/boards/278?selectedIssue=CPP-141)

[CPP-141] Using js-cookies to remove cookies

---

snapshot.gql
src/components/SharedBlocks/BlocksRenderer.tsx
src/components/SharedBlocks/CtaBanner/CtaBanner.sass
src/components/SharedBlocks/CtaBanner/CtaBanner.tsx
src/components/SharedBlocks/HeroSlider/HeroSlider.sass
src/components/SharedBlocks/HeroSlider/HeroSlider.tsx
src/components/SharedBlocks/Intro/Intro.tsx
src/components/SharedBlocks/VisualText/VisualText.tsx
src/partials/Cta/Cta.sass
src/sass/app.sass

- HeroSlider
- added slug or id to hero slider
- Intro component fix
- scroll margin to clocks component
- added video to slider
- increased slide 
- CtaBanner
- added light CtaBanner variant
- added black & black-hollow to cta variant
- decreased CtaBanner top 
- VisualText
- decreased bottom margin
- video and image share the same style
Depends on this [pull request](https://github.com/pagopa/cms-corporate-backend/pull/28)
Fixes # [SELC-2735](https://pagopa.atlassian.net/browse/SELC-2735)
[SELC-2735]: https://pagopa.atlassian.net/browse/SELC-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-2735] Cms people page changerequest

---

src/components/Jobposition/JobPage/JobPage.tsx

Changes the iframe src to use the new sapsf job application form
Fixes # [cpp-143](https://pagopa.atlassian.net/browse/CPP-143)

[CPP-143] sapsf job application

---

src/components/SharedBlocks/Jobposition/JobpositionList.tsx

- Current date is now compared to the 00:00 am of 
the day following the closeDate
Job positions were considered closed on the same day of the close date.
- The new function is been tested only in a node environment

Fix: [CPP-144] jobposition expiration

---

src/components/SharedBlocks/Jobposition/JobpositionList.tsx

update wording of a box in job position list

box job position list
